name: Jonathan_Denard
description: A new Flutter project.

publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.0
  flutter_custom_clippers: ^1.1.2
  line_icons: ^0.2.0
  shared_preferences: ^0.5.12+4
  firebase_core: ^0.4.5
  firebase_auth: ^0.16.0
  cloud_firestore: ^0.13.5
  flutter_spinkit: ^4.1.2+1
  firebase_storage: ^3.1.6
  firebase_messaging: ^5.0.4
  file_picker: ^1.12.0
  uuid: ^2.2.0



dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true
  assets:
  - assets/

